
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MASMAS = 43;
  public static final int MENOSMENOS = 44;
  public static final int POR = 39;
  public static final int CHAR = 6;
  public static final int ENTERO = 56;
  public static final int XOR = 54;
  public static final int DIFERENTE = 46;
  public static final int CASE = 11;
  public static final int DOUBLE = 4;
  public static final int CONTINUE = 17;
  public static final int INT = 3;
  public static final int COR_DER = 32;
  public static final int LLAVE_C = 30;
  public static final int FOR = 14;
  public static final int LLAVE_A = 29;
  public static final int NOT = 53;
  public static final int AND = 51;
  public static final int MENORIGUAL = 48;
  public static final int IGUAL = 36;
  public static final int APPEND = 25;
  public static final int OR = 52;
  public static final int BOOL = 5;
  public static final int DIV = 40;
  public static final int UMENOS = 55;
  public static final int IF = 8;
  public static final int ID = 60;
  public static final int MAYORIGUAL = 50;
  public static final int DECIMAL = 57;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int TRUE = 21;
  public static final int NEW = 23;
  public static final int error = 1;
  public static final int COMA = 34;
  public static final int LIT_STRING = 58;
  public static final int MENOS = 38;
  public static final int MENOR = 47;
  public static final int LIT_CHAR = 59;
  public static final int MOD = 41;
  public static final int PAR_C = 28;
  public static final int START = 20;
  public static final int BREAK = 16;
  public static final int PAR_A = 27;
  public static final int SWITCH = 10;
  public static final int MAYOR = 49;
  public static final int POTENCIA = 42;
  public static final int DOSPTOS = 33;
  public static final int ELSE = 9;
  public static final int PUNTO = 35;
  public static final int IGUALIGUAL = 45;
  public static final int WHILE = 13;
  public static final int LIST = 24;
  public static final int DEFAULT = 12;
  public static final int COR_IZQ = 31;
  public static final int PTCOMA = 26;
  public static final int STRING = 7;
  public static final int FALSE = 22;
  public static final int VAR = 2;
  public static final int PRINT = 19;
  public static final int DO = 15;
  public static final int MAS = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VAR",
  "INT",
  "DOUBLE",
  "BOOL",
  "CHAR",
  "STRING",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "WHILE",
  "FOR",
  "DO",
  "BREAK",
  "CONTINUE",
  "RETURN",
  "PRINT",
  "START",
  "TRUE",
  "FALSE",
  "NEW",
  "LIST",
  "APPEND",
  "PTCOMA",
  "PAR_A",
  "PAR_C",
  "LLAVE_A",
  "LLAVE_C",
  "COR_IZQ",
  "COR_DER",
  "DOSPTOS",
  "COMA",
  "PUNTO",
  "IGUAL",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "MOD",
  "POTENCIA",
  "MASMAS",
  "MENOSMENOS",
  "IGUALIGUAL",
  "DIFERENTE",
  "MENOR",
  "MENORIGUAL",
  "MAYOR",
  "MAYORIGUAL",
  "AND",
  "OR",
  "NOT",
  "XOR",
  "UMENOS",
  "ENTERO",
  "DECIMAL",
  "LIT_STRING",
  "LIT_CHAR",
  "ID"
  };
}

