
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MASMAS = 39;
  public static final int MENOSMENOS = 40;
  public static final int POR = 35;
  public static final int CHAR = 5;
  public static final int FIND = 26;
  public static final int REMOVE = 30;
  public static final int ENTERO = 63;
  public static final int XOR = 50;
  public static final int DIFERENTE = 42;
  public static final int CASE = 12;
  public static final int DOUBLE = 3;
  public static final int CONTINUE = 18;
  public static final int INT = 2;
  public static final int PRINTLN = 22;
  public static final int COR_DER = 56;
  public static final int LLAVE_C = 54;
  public static final int LLAVE_A = 53;
  public static final int FOR = 16;
  public static final int NOT = 49;
  public static final int AND = 47;
  public static final int MENORIGUAL = 44;
  public static final int IGUAL = 61;
  public static final int APPEND = 29;
  public static final int OR = 48;
  public static final int BOOL = 4;
  public static final int DIV = 36;
  public static final int IF = 9;
  public static final int ID = 62;
  public static final int MAYORIGUAL = 46;
  public static final int DECIMAL = 64;
  public static final int EOF = 0;
  public static final int RETURN = 19;
  public static final int TRUE = 31;
  public static final int NEW = 27;
  public static final int error = 1;
  public static final int COMA = 59;
  public static final int LIT_STRING = 65;
  public static final int MENOS = 34;
  public static final int MENOR = 43;
  public static final int LIT_CHAR = 66;
  public static final int PAR_C = 52;
  public static final int MOD = 38;
  public static final int PAR_A = 51;
  public static final int BREAK = 17;
  public static final int TOSTRING = 25;
  public static final int VOID = 7;
  public static final int SWITCH = 11;
  public static final int MAYOR = 45;
  public static final int POTENCIA = 37;
  public static final int DOSPTOS = 58;
  public static final int ELSE = 10;
  public static final int PUNTO = 60;
  public static final int IGUALIGUAL = 41;
  public static final int START_WITH = 20;
  public static final int WHILE = 14;
  public static final int LIST = 28;
  public static final int DEFAULT = 13;
  public static final int COR_IZQ = 55;
  public static final int PTCOMA = 57;
  public static final int STRING = 6;
  public static final int FALSE = 32;
  public static final int VAR = 8;
  public static final int PRINT = 21;
  public static final int LENGTH = 23;
  public static final int ROUND = 24;
  public static final int DO = 15;
  public static final int MAS = 33;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "DOUBLE",
  "BOOL",
  "CHAR",
  "STRING",
  "VOID",
  "VAR",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "WHILE",
  "DO",
  "FOR",
  "BREAK",
  "CONTINUE",
  "RETURN",
  "START_WITH",
  "PRINT",
  "PRINTLN",
  "LENGTH",
  "ROUND",
  "TOSTRING",
  "FIND",
  "NEW",
  "LIST",
  "APPEND",
  "REMOVE",
  "TRUE",
  "FALSE",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "POTENCIA",
  "MOD",
  "MASMAS",
  "MENOSMENOS",
  "IGUALIGUAL",
  "DIFERENTE",
  "MENOR",
  "MENORIGUAL",
  "MAYOR",
  "MAYORIGUAL",
  "AND",
  "OR",
  "NOT",
  "XOR",
  "PAR_A",
  "PAR_C",
  "LLAVE_A",
  "LLAVE_C",
  "COR_IZQ",
  "COR_DER",
  "PTCOMA",
  "DOSPTOS",
  "COMA",
  "PUNTO",
  "IGUAL",
  "ID",
  "ENTERO",
  "DECIMAL",
  "LIT_STRING",
  "LIT_CHAR"
  };
}

